require:
- rubocop-performance
- rubocop-rspec

Lint/RaiseException:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
