require:
- rubocop-performance
- rubocop-rspec

Layout/LineLength:
  Max: 140

Lint/RaiseException:
  Enabled: true

Metrics/BlockLength:
  Max: 75

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
